dotenv_constants = {
    "FRESHDESK_DOMAIN":"<FRESHDESK_DOMAIN>",
    "FRESHDESK_API":"<FRESHDESK_API>",
    "REQUESTER_NAME":"<REQUESTER_NAME>",
    "REQUESTER_EMAIL":"<REQUESTER_EMAIL>",
    "SMTP_SERVER":"<SMTP_SERVER>",
    "SMTP_EMAIL":"<SMTP_EMAIL>",
    "SMTP_PASSWORD":"<SMTP_PASSWORD>",
    "SMTP_PORT":"587",
    "SENDER_NAME":"<SENDER_NAME>",
    "SENDER_EMAIL":"<SENDER_EMAIL>",
    "SENDER_DEPARTMENT":"Engineering",
    "VERSION_FOLDER":"MQL5",
    "PACKAGE_NAME":"<PACKAGE_NAME>"
}