from init_constants import DIR_ROOT

dotenv_constants = {
    "BASE_DIRECTORY":f"{DIR_ROOT}",
    "FRESHDESK_DOMAIN":"<FRESHDESK_DOMAIN>",
    "FRESHDESK_API":"<FRESHDESK_API>",
    "GITHUB_USERNAME":"<GIT USERNAME>",
    "GITHUB_TOKEN":"<GITHUB_TOKEN>",
    "REQUESTER_NAME":"<REQUESTER_NAME>",
    "REQUESTER_EMAIL":"<REQUESTER_EMAIL>",
    "SMTP_SERVER":"<SMTP_SERVER>",
    "SMTP_EMAIL":"<SMTP_EMAIL>",
    "SMTP_PASSWORD":"<SMTP_PASSWORD>",
    "SMTP_PORT":"587",
    "SENDER_NAME":"<SENDER_NAME>",
    "SENDER_EMAIL":"<SENDER_EMAIL>",
    "SENDER_DEPARTMENT":"Engineering",
    "VERSION_FOLDER":"MQL5",
}